name: Build Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone qmk
        run: git clone https://github.com/qmk/qmk_firmware.git
      - name: Install qmk deps
        run: cd qmk_firmware && ./util/qmk_install.sh && python3 -m pip install qmk
      - name: fix gcc
        run: sudo bash .github/scripts/update-gcc10-ubuntu.sh
      - name: Install git submodules
        run: cd qmk_firmware && make git-submodule
      - name: Link keymap
        run: ln -s ../../../../shurizzle qmk_firmware/keyboards/crkbd/keymaps/shurizzle
      - name: Compile firmware
        run: cd qmk_firmware && qmk compile -kb crkbd/r2g -km shurizzle
      - name: Upload compiled firmware (build artifact)
        uses: actions/upload-artifact@v4
        with:
          name: Keychron crkbd r2g QMK Firmware
          path: qmk_firmware/crkbd_r2g_shurizzle.hex
      - name: Upload compiled firmware (tagged release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qmk_firmware/crkbd_r2g_shurizzle.hex
